version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    labels:
      - "cause::dependency"
      - "type::chore"
      - "automation::dependabot"
      - "ecosystem::rust"
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    labels:
      - "cause::dependency"
      - "type::chore"
      - "automation::dependabot"
      - "ecosystem::actions"
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
