[workspace]
resolver = "3"
members = ["gitarena", "gitarena-common", "gitarena-macros", "gitarena-ssh", "gitarena-workhorse"]

[workspace.package]
version = "0.0.0"
authors = ["Mari <me@mari.zip>"]
description = "Software development platform with built-in vcs, issue tracking and code review"
edition = "2024"
license = "MIT"
repository = "https://github.com/mellowagain/gitarena"
readme = "README.md"

[workspace.dependencies]
sqlx = { version = "0.8.6", features = ["chrono", "ipnetwork", "json", "postgres", "runtime-tokio", "tls-rustls-ring-webpki", "uuid"] }
ipnetwork = { version = "=0.21.1", features = ["serde"] } # needs to be in sync with the version sqlx uses^
opentelemetry = "0.31.0"
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.31.1", features = ["grpc-tonic", "tls-webpki-roots", "http-proto", "http-json", "reqwest-rustls-webpki-roots"] }
opentelemetry-semantic-conventions = "0.31.0"
opentelemetry-appender-tracing = { version = "0.31.1", default-features = false, features = ["log"] }
tracing-opentelemetry = "0.32.1"
russh = { version = "0.60.2", features = ["aws-lc-rs", "serde"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
used_underscore_binding = "allow"
enum_glob_use = "allow"
items_after_statements = "allow"
doc_markdown = "allow"

[profile.release]
lto = true

[patch.crates-io]
gitarena-macros = { path = "gitarena-macros" }
