[workspace]
resolver = "3"
members = ["gitarena", "gitarena-macros"]

[workspace.package]
version = "0.0.0"
authors = ["Mari <me@mari.zip>"]
description = "Software development platform with built-in vcs, issue tracking and code review"
edition = "2024"
license = "MIT"
repository = "https://github.com/mellowagain/gitarena"
readme = "README.md"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(tokio_unstable)"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
used_underscore_binding = "allow"
enum_glob_use = "allow"
items_after_statements = "allow"
doc_markdown = "allow"
struct_excessive_bools = "allow"
unused_self = "allow"

[profile.release]
lto = true

[patch.crates-io]
gitarena-macros = { path = "gitarena-macros" }
