services:
  postgres:
    image: postgres:trixie
    environment:
      POSTGRES_DB: gitarena
      POSTGRES_USER: gitarena
      POSTGRES_PASSWORD: gitarena
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitarena"]
      interval: 5s
      timeout: 3s
      retries: 5

  gitarena:
    build: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - repos:repositories
    environment:
      # TODO: Remove this once nginx is also added to this compose
      SERVE_STATIC_FILES: true
      DATABASE_URL: "postgresql://gitarena@gitarena:5432/gitarena?sslmode=disable"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  repos:
