[package]
name = "gitarena-common"
version = "0.0.0"
authors = ["mellowagain <me@cutegirl.tech>"]
edition = "2021"

[dependencies]
bincode = "1.3.3"
gitarena-macros = "0.0.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
serde = { version = "1.0.133", features = ["derive"] }
