[package]
name = "gitarena-macros"
version = { workspace = true }
authors = { workspace = true }
description = "Helper macros for GitArena"
edition = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.106", features = ["full"] }
