[package]
name = "gitarena-workhorse"
version = { workspace = true }
authors = { workspace = true }
description = "GitArena daemon"
edition = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = "1.0.102"
console-subscriber = { version = "0.5.0", features = ["parking_lot"] }
futures = "0.3.32"
futures-locks = "0.7.0"
gitarena-common = { version = "0.0.0", path = "../gitarena-common" }
parity-tokio-ipc = "0.9.0"
tokio = { version = "1.50.0", features = ["full", "tracing"] }
tracing = "0.1.29"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.6", features = ["env-filter", "json", "std"] }
tracing-unwrap = "1.0.1"
