name: Frontend CI

on:
  - push
  - pull_request_target

permissions:
  contents: read

env:
  NEXT_TELEMETRY_DISABLED: 1

defaults:
  run:
    working-directory: gitarena-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          version: 10
          package_json_file: gitarena-frontend/package.json
          run_install: |
            - cwd: gitarena-frontend
              args: [--frozen-lockfile]

      - name: next.js cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ${{ github.workspace }}/gitarena-frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: build
        run: pnpm run build

      - name: format check
        run: pnpm run format:check

      - name: lint
        run: pnpm run lint
