name: Frontend CI

on:
  - push
  - pull_request_target

permissions:
  contents: read

env:
  NEXT_TELEMETRY_DISABLED: 1

defaults:
  run:
    working-directory: gitarena-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
          package_json_file: gitarena-frontend/package.json
          run_install: |
            - cwd: gitarena-frontend
              args: [--frozen-lockfile]

      - name: next.js cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ${{ github.workspace }}/gitarena-frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: build
        run: pnpm run build

      - name: format check
        run: pnpm run format:check

      - name: lint
        run: pnpm run lint
